# Generated by Django 5.0.2 on 2024-02-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_is_visible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'default_related_name': 'news', 'managed': True, 'ordering': ('-created', '-news_id'), 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
    ]
