# Generated by Django 5.2.2 on 2026-02-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCategory',
            fields=[
                ('category_id', models.AutoField(db_column='category_id', help_text='Auto-generated ID number of the note category.', primary_key=True, serialize=False, verbose_name='Note Category ID')),
                ('category_name', models.CharField(db_column='name', help_text='Name of the note category.', max_length=64, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Note Category',
                'verbose_name_plural': 'Notes Categories',
                'db_table': 'note_categories',
                'ordering': ('category_name',),
                'managed': True,
                'default_related_name': 'note_categories',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(help_text='Auto-generated ID number of the note.', primary_key=True, serialize=False, verbose_name='Note ID')),
                ('name', models.CharField(db_column='name', help_text='Name of the note.', max_length=64, unique=True, verbose_name='Name')),
                ('body', models.TextField(db_column='body', help_text='Body of the note.', verbose_name='Note')),
                ('note_file', models.FileField(help_text='PDF file related the note.', upload_to='notes/', verbose_name='Note File')),
                ('category', models.ForeignKey(db_column='category_id', help_text='Category of the note.', on_delete=django.db.models.deletion.PROTECT, related_name='notes', related_query_name='note', to='notes.notecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ('name',),
                'managed': True,
                'default_related_name': 'notes',
            },
        ),
    ]
