# Generated by Django 5.2.2 on 2026-02-25 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(blank=True, db_column='body', help_text='Body of the note.', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', help_text='Category of the note.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes', related_query_name='note', to='notes.notecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(blank=True, help_text='PDF file related the note.', null=True, upload_to='notes/', verbose_name='Note File'),
        ),
    ]
