# Generated by Django 5.0.3 on 2024-03-06 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUDProcess',
            fields=[
                ('process_id', models.PositiveIntegerField(db_column='process_id', help_text='MUD process ID (PID) on the server.', primary_key=True, serialize=False, verbose_name='MUD Process ID (PID)')),
                ('name', models.CharField(db_column='name', default='ishar', help_text='Name of the MUD process.', max_length=32, verbose_name='Name')),
                ('user', models.CharField(db_column='user', help_text='User running the MUD process.', max_length=32, verbose_name='User')),
                ('last_updated', models.DateTimeField(db_column='last_updated', default=django.utils.timezone.now, help_text='Date and time the MUD process was last updated in the database.', verbose_name='Last Updated')),
                ('created', models.DateTimeField(db_column='created', default=None, help_text='Date and time the MUD process was created (last restarted).', null=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'MUD Process',
                'verbose_name_plural': 'MUD Processes',
                'db_table': 'mud_processes',
                'ordering': ('-last_updated',),
                'managed': True,
                'default_related_name': 'process',
            },
        ),
    ]
