# Generated by Django 4.2.4 on 2023-09-20 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(help_text='Auto-generated permanent ID number of the news post.', primary_key=True, serialize=False, verbose_name='News ID')),
                ('created', models.DateTimeField(db_column='created', default=django.utils.timezone.now, help_text='Date and time when the news post was created.', verbose_name='Created')),
                ('subject', models.CharField(db_column='subject', help_text='Subject of the news post.', max_length=64, verbose_name='Subject')),
                ('body', models.TextField(db_column='body', help_text='Body of the news post.', verbose_name='Body')),
                ('is_visible', models.BooleanField(default=True, help_text='Should the patch be visible publicly?', verbose_name='Is Visible?')),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account that created the news post.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
                'ordering': ('-created', '-news_id'),
                'managed': True,
                'default_related_name': 'news',
            },
        ),
    ]
