# Generated by Django 5.0.8 on 2024-09-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'default_related_name': 'news', 'get_latest_by': ('is_visible', 'created'), 'managed': True, 'ordering': ('-created', '-news_id'), 'verbose_name': 'News Post', 'verbose_name_plural': 'News Posts'},
        ),
    ]
