# Generated by Django 4.2.7 on 2024-01-12 00:43

import django.core.validators
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_alter_patch_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_file',
            field=models.FileField(help_text='PDF file of the patch.', upload_to=pathlib.PurePosixPath('/Users/eric/code/ishar-web/media/patches'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Patch File'),
        ),
    ]
