# Generated by Django 4.2.4 on 2023-09-10 00:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('patch_id', models.AutoField(help_text='Auto-generated, permanent ID number of the patch.', primary_key=True, serialize=False, verbose_name='Patch ID')),
                ('patch_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the patch to sort/display on the website.', verbose_name='Patch Date')),
                ('patch_name', models.CharField(help_text='Name of the patch.', max_length=64, unique=True, verbose_name='Patch Name')),
                ('patch_file', models.FileField(help_text='PDF file of the patch.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Patch File')),
                ('is_visible', models.BooleanField(default=True, help_text='Should the patch be visible publicly?', verbose_name='Is Visible?')),
                ('account', models.ForeignKey(help_text='Account responsible for the patch.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Patch',
                'verbose_name_plural': 'Patches',
                'db_table': 'patches',
                'ordering': ('-patch_date',),
                'managed': True,
            },
        ),
    ]
