# Generated by Django 5.0.2 on 2024-02-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_alter_patch_patch_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patch',
            options={'default_related_name': 'patch', 'managed': True, 'ordering': ('-patch_date',), 'verbose_name': 'Patch', 'verbose_name_plural': 'Patches'},
        ),
    ]
