# Generated by Django 5.0.2 on 2024-03-06 02:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mudprocess_name_alter_mudprocess_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mudprocess',
            options={'default_related_name': 'process', 'managed': True, 'ordering': ('-last_updated',), 'verbose_name': 'MUD Process', 'verbose_name_plural': 'MUD Processes'},
        ),
        migrations.AddField(
            model_name='mudprocess',
            name='created',
            field=models.DateTimeField(db_column='created', default=None, help_text='Date and time the MUD process was created (last restarted).', null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='mudprocess',
            name='last_updated',
            field=models.DateTimeField(db_column='last_updated', default=django.utils.timezone.now, help_text='Date and time the MUD process was last updated in the database.', verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='mudprocess',
            name='user',
            field=models.CharField(db_column='user', help_text='User running the MUD process.', max_length=32, verbose_name='User'),
        ),
    ]
