# Generated by Django 5.2.16 on 2026-07-17 14:58

import apps.core.models.unsigned
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebLoginToken",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        help_text="SHA-256 hex of the token; the plaintext is never stored.",
                        max_length=64,
                        unique=True,
                        verbose_name="Token Hash",
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(
                        db_column="account_id",
                        help_text="Account the token was minted for.",
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the token was minted.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Mint time + 90 seconds; the game refuses the token after.",
                        verbose_name="Expires At",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        help_text="When the game consumed the token (single use).",
                        null=True,
                        verbose_name="Used At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Login Token",
                "verbose_name_plural": "Web Login Tokens",
                "db_table": "web_login_token",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RoomDiscovery",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Account that discovered the room.",
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "room_vnum",
                    models.IntegerField(
                        help_text="VNUM of the discovered room.",
                        verbose_name="Room VNUM",
                    ),
                ),
                (
                    "zone_id",
                    models.IntegerField(
                        help_text="Zone of the room (denormalized, resolved server-side).",
                        verbose_name="Zone ID",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the account first saw the room.",
                        verbose_name="First Seen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Discovery",
                "verbose_name_plural": "Room Discoveries",
                "db_table": "web_room_discovery",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["account_id", "zone_id"],
                        name="web_room_di_account_d0db94_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_id", "room_vnum"), name="uniq_account_room"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomNote",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Account the note belongs to.",
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "room_vnum",
                    models.IntegerField(
                        help_text="VNUM of the room the note is about.",
                        verbose_name="Room VNUM",
                    ),
                ),
                (
                    "zone_id",
                    models.IntegerField(
                        help_text="Zone of the room (denormalized, resolved server-side).",
                        verbose_name="Zone ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Note text (capped at 2000 characters by the view).",
                        verbose_name="Text",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the note was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the note was last edited.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Note",
                "verbose_name_plural": "Room Notes",
                "db_table": "web_room_note",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["account_id", "zone_id"],
                        name="web_room_no_account_287114_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_id", "room_vnum"),
                        name="uniq_account_room_note",
                    )
                ],
            },
        ),
    ]
