# Generated by Django 5.2.16 on 2026-07-19 13:08

import apps.core.models.unsigned
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestTrack",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Account tracking the quest.",
                        verbose_name="Account ID",
                    ),
                ),
                (
                    "quest_id",
                    models.IntegerField(
                        help_text="Quest ID being tracked (game quests table key).",
                        verbose_name="Quest ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the quest was tracked.",
                        verbose_name="Created At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quest Track",
                "verbose_name_plural": "Quest Tracks",
                "db_table": "web_quest_track",
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account_id", "quest_id"),
                        name="uniq_account_quest_track",
                    )
                ],
            },
        ),
    ]
