# Generated by Django 5.0.8 on 2024-10-05 18:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('submission_id', models.AutoField(db_column='submission_id', help_text='Auto-generated permanent ID number of the feedback submission.', primary_key=True, serialize=False, verbose_name='Submission ID')),
                ('submission_type', models.PositiveIntegerField(choices=[(-1, 'Complete'), (0, 'Other'), (1, 'Bug Report'), (2, 'Idea / Suggestion')], db_column='submission_type', default=0, help_text='Type of the feedback submission.', verbose_name='Type')),
                ('subject', models.CharField(db_column='subject', help_text='Subject of the feedback submission.', max_length=64, validators=[django.core.validators.MinLengthValidator(limit_value=1), django.core.validators.MaxLengthValidator(limit_value=64)], verbose_name='Subject')),
                ('body_text', models.TextField(db_column='body_text', help_text='Body text of the feedback submission.', verbose_name='Message')),
                ('submitted', models.DateTimeField(auto_now_add=True, db_column='submitted', help_text='Date and time when the feedback was submitted.', verbose_name='Submitted')),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account that submitted the feedback.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Feedback Submission',
                'verbose_name_plural': 'Feedback Submissions',
                'db_table': 'feedback',
                'ordering': ('-submitted',),
                'get_latest_by': ('submitted',),
                'managed': True,
                'default_related_name': 'submission',
            },
        ),
    ]
