# Generated by Django 5.0.8 on 2024-10-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacksubmission',
            name='submission_type',
            field=models.IntegerField(choices=[(-1, 'Complete'), (0, 'Other'), (1, 'Bug Report'), (2, 'Idea / Suggestion')], db_column='submission_type', default=0, help_text='Type of the feedback submission.', verbose_name='Type'),
        ),
    ]
