# Generated by Django 5.0.8 on 2024-10-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedbacksubmission_submission_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksubmission',
            options={'default_related_name': 'submission', 'get_latest_by': ('submitted',), 'managed': True, 'ordering': ('-submitted',), 'verbose_name': 'Submission', 'verbose_name_plural': 'Submissions'},
        ),
    ]
