# Generated by Django 5.0.8 on 2024-10-06 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedbacksubmission_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksubmission',
            name='private',
            field=models.BooleanField(db_column='private', default=False, help_text='Should the feedback submission be private?', verbose_name='Private?'),
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('comment_id', models.AutoField(db_column='comment_id', help_text='Auto-generated permanent ID number of the feedback comment.', primary_key=True, serialize=False, verbose_name='Comment ID')),
                ('body_text', models.TextField(db_column='body_text', help_text='Body text of the feedback comment.', verbose_name='Message')),
                ('submitted', models.DateTimeField(auto_now_add=True, db_column='submitted', help_text='Date and time when the comment was submitted.', verbose_name='Submitted')),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account that submitted the feedback comment.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
                ('feedback_submission', models.ForeignKey(db_column='submission_id', help_text='Account that submitted the feedback comment.', on_delete=django.db.models.deletion.DO_NOTHING, to='feedback.feedbacksubmission', verbose_name='Feedback Submission')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'feedback_comments',
                'ordering': ('-submitted',),
                'get_latest_by': ('submitted',),
                'managed': True,
                'default_related_name': 'comment',
            },
        ),
    ]
