# Generated by Django 5.1.2 on 2024-10-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_feedbackvote_delete_feedbackcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacksubmission',
            name='private',
        ),
    ]
