# Generated by Django 5.1.2 on 2024-10-26 01:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedbacksubmission_submission_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="feedbackvote",
            name="one_vote_per",
        ),
        migrations.AddConstraint(
            model_name="feedbackvote",
            constraint=models.UniqueConstraint(
                fields=("account", "feedback_submission"), name="one_vote_per_feedback"
            ),
        ),
    ]
