# Generated by Django 5.2 on 2026-07-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "survey_id",
                    models.AutoField(
                        help_text="Auto-generated ID number of the survey.",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Survey ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL identifier of the survey (/surveys/<slug>/).",
                        max_length=64,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the survey.",
                        max_length=128,
                        verbose_name="Title",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Introduction shown above the survey form.",
                        verbose_name="Introduction",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        help_text="Draft surveys are invisible to players; only Open surveys accept submissions (further narrowed by the schedule window, if set).",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "opens_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: while Open, accept no submissions before this time.",
                        null=True,
                        verbose_name="Opens At",
                    ),
                ),
                (
                    "closes_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: while Open, accept no submissions from this time on.",
                        null=True,
                        verbose_name="Closes At",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Survey",
                "verbose_name_plural": "Surveys",
                "db_table": "surveys",
                "ordering": ("-survey_id",),
                "managed": True,
                "default_related_name": "surveys",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "question_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Question ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order of the question within its section.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("single", "Single choice"),
                            ("multi", "Multiple choice"),
                            ("matrix", "Matrix (rate each row)"),
                            ("rank", "Ranked picks"),
                            ("text", "Free text"),
                        ],
                        default="single",
                        max_length=8,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="The question itself.",
                        max_length=255,
                        verbose_name="Question",
                    ),
                ),
                (
                    "hint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional helper text shown under the question.",
                        max_length=255,
                        verbose_name="Hint",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether an answer is required to submit the survey.",
                        verbose_name="Required?",
                    ),
                ),
                (
                    "max_choices",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Multiple choice: maximum picks allowed (blank = unlimited). Ranked picks: how many ranked slots (e.g. 2 = rank your top 2).",
                        null=True,
                        verbose_name="Max Choices",
                    ),
                ),
                (
                    "allow_other",
                    models.BooleanField(
                        default=False,
                        help_text='Offer an "Other: ___" write-in alongside the options.',
                        verbose_name='Allow "Other"?',
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        related_query_name="question",
                        to="surveys.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Question",
                "verbose_name_plural": "Survey Questions",
                "db_table": "survey_questions",
                "ordering": ("survey", "section__position", "position", "question_id"),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SurveyOption",
            fields=[
                (
                    "option_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Option ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order of the option within the question.",
                        verbose_name="Position",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text")),
                (
                    "is_matrix_row",
                    models.BooleanField(
                        default=False,
                        help_text="Matrix questions only: this option is a rated row rather than a point on the rating scale.",
                        verbose_name="Matrix Row?",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        related_query_name="option",
                        to="surveys.surveyquestion",
                        verbose_name="Question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Option",
                "verbose_name_plural": "Survey Options",
                "db_table": "survey_options",
                "ordering": ("question", "position", "option_id"),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SurveySection",
            fields=[
                (
                    "section_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Section ID"
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Order of the section within the survey.",
                        verbose_name="Position",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Section heading.",
                        max_length=128,
                        verbose_name="Title",
                    ),
                ),
                (
                    "preamble",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional framing text shown under the section heading.",
                        verbose_name="Preamble",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        related_query_name="section",
                        to="surveys.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Section",
                "verbose_name_plural": "Survey Sections",
                "db_table": "survey_sections",
                "ordering": ("survey", "position", "section_id"),
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="Section this question appears under (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                related_query_name="question",
                to="surveys.surveysection",
                verbose_name="Section",
            ),
        ),
        migrations.CreateModel(
            name="SurveySubmission",
            fields=[
                (
                    "submission_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Submission ID"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        db_column="account_id",
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_submissions",
                        related_query_name="survey_submission",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Account",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        related_query_name="submission",
                        to="surveys.survey",
                        verbose_name="Survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Submission",
                "verbose_name_plural": "Survey Submissions",
                "db_table": "survey_submissions",
                "ordering": ("-submission_id",),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "answer_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Answer ID"
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Ranked picks only: 1 = first pick.",
                        null=True,
                        verbose_name="Rank",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='Free-text answer or an "Other" write-in.',
                        verbose_name="Text",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        help_text="The picked choice (None for free text / an Other write-in).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="answer",
                        to="surveys.surveyoption",
                        verbose_name="Option",
                    ),
                ),
                (
                    "row",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matrix questions only: the row this rating applies to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_answers",
                        related_query_name="row_answer",
                        to="surveys.surveyoption",
                        verbose_name="Matrix Row",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="answer",
                        to="surveys.surveyquestion",
                        verbose_name="Question",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="answer",
                        to="surveys.surveysubmission",
                        verbose_name="Submission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Survey Answer",
                "verbose_name_plural": "Survey Answers",
                "db_table": "survey_answers",
                "ordering": ("submission", "question", "rank", "answer_id"),
                "managed": True,
            },
        ),
        migrations.AddConstraint(
            model_name="surveysubmission",
            constraint=models.UniqueConstraint(
                fields=("survey", "account"), name="one_submission_per_account"
            ),
        ),
    ]
