from .accounts import AccountsConfig
from .challenges import ChallengesConfig
from .classes import ClassesConfig
from .clients import ClientsConfig
from .core import CoreConfig
from .discord import DiscordConfig
from .events import EventsConfig
from .faqs import FAQsConfig
from .help import HelpConfig
from .leaders import LeadersConfig
from .mobiles import MobilesConfig
from .news import NewsConfig
from .patches import PatchesConfig
from .players import PlayersConfig
from .quests import QuestsConfig
from .races import RacesConfig
from .seasons import SeasonsConfig
from .skills import SkillsConfig
