# Generated by Django 4.2.7 on 2023-11-09 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mudclientcategory',
            options={'default_related_name': 'mud_client_categories', 'managed': True, 'ordering': ('display_order',), 'verbose_name': 'MUD Client Category', 'verbose_name_plural': 'MUD Client Categories'},
        ),
    ]
