# Generated by Django 4.2.7 on 2023-11-09 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_mudclient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mudclient',
            name='name',
            field=models.CharField(db_column='name', help_text='Name of the MUD client.', max_length=64, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mudclientcategory',
            name='name',
            field=models.CharField(db_column='name', help_text='Name of the MUD client category.', max_length=64, verbose_name='Category Name'),
        ),
    ]
