# Generated by Django 5.1.2 on 2024-10-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_mudclient_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mudclientcategory",
            name="display_order",
            field=models.PositiveIntegerField(
                db_column="display_order",
                help_text="What is the numeric display order of the MUD client category?",
                unique=True,
                verbose_name="(Display) Order",
            ),
        ),
    ]
