# Generated by Django 5.1.2 on 2024-10-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0006_alter_mudclientcategory_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="mudclientcategory",
            name="display_icon",
            field=models.CharField(
                blank=True,
                db_column="display_icon",
                help_text="Bootstrap icon to display with the MUD client category.",
                max_length=64,
                null=True,
                verbose_name="(Display) Icon",
            ),
        ),
    ]
