from .accounts import AccountsConfig
from .achievements import AchievementsConfig
from .challenges import ChallengesConfig
from .classes import ClassesConfig
from .clients import ClientsConfig
from .conditions import ConditionsConfig
from .core import CoreConfig
from .discord import DiscordConfig
from .events import EventsConfig
from .faqs import FAQsConfig
from .feedback import FeedbackConfig
from .help import HelpConfig
from .history import HistoryConfig
from .leaders import LeadersConfig
from .mobiles import MobilesConfig
from .news import NewsConfig
from .objects import ObjectsConfig
from .patches import PatchesConfig
from .players import PlayersConfig
from .processes import ProcessesConfig
from .quests import QuestsConfig
from .races import RacesConfig
from .rooms import RoomsConfig
from .seasons import SeasonsConfig
from .skills import SkillsConfig
