# Generated by Django 4.2.7 on 2023-11-07 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(help_text='Auto-generated permanent ID number of the question.', primary_key=True, serialize=False, verbose_name='FAQ ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created', help_text='Date and time when the question was created.', verbose_name='Created')),
                ('question_text', models.CharField(db_column='question_text', help_text='Text of the question.', max_length=64, verbose_name='Question')),
                ('question_answer', models.TextField(db_column='question_answer', help_text='Answer to the question.', verbose_name='Answer')),
                ('is_visible', models.BooleanField(db_column='is_visible', default=True, help_text='Should the question be visible publicly?', verbose_name='Visible?')),
                ('display_order', models.PositiveIntegerField(db_column='display_order', help_text='What is the numeric display order of the question?', unique=True, verbose_name='Display Order')),
                ('account', models.ForeignKey(db_column='account_id', help_text='Account that created the question.', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Frequently Asked Question',
                'verbose_name_plural': 'Frequently Asked Questions',
                'db_table': 'faqs',
                'ordering': ('display_order',),
                'managed': True,
                'default_related_name': 'faqs',
            },
        ),
    ]
