# Generated by Django 4.2.7 on 2023-11-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_text',
            field=models.TextField(db_column='question_text', help_text='Text of the question.', verbose_name='Question'),
        ),
    ]
