# Generated by Django 5.2.16 on 2026-07-15 10:39

import apps.core.models.unsigned
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatchNote",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Patch Note ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_column="title",
                        help_text="Title of the patch note.",
                        max_length=80,
                        verbose_name="Title",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        db_column="body",
                        help_text="Body (lightweight markdown: ## headers, - bullets, **bold**).",
                        verbose_name="Body",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        db_column="author",
                        default="System",
                        help_text="Author attribution shown to players.",
                        max_length=30,
                        verbose_name="Author",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_column="is_published",
                        default=False,
                        help_text="Published notes are visible to players; drafts are staff-only.",
                        verbose_name="Published?",
                    ),
                ),
                (
                    "season_id",
                    models.PositiveIntegerField(
                        blank=True,
                        db_column="season_id",
                        help_text="Optional season this note belongs to.",
                        null=True,
                        verbose_name="Season",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="created_at",
                        help_text="When the draft was created.",
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="published_at",
                        help_text="When the note was published.",
                        null=True,
                        verbose_name="Published At",
                    ),
                ),
                (
                    "discord_sent_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="discord_sent_at",
                        help_text="When the game posted the Discord announcement.",
                        null=True,
                        verbose_name="Discord Sent At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patch Note",
                "verbose_name_plural": "Patch Notes",
                "db_table": "patch_notes",
                "ordering": ("-published_at", "-created_at", "-id"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PatchNoteSyncTask",
            fields=[
                (
                    "id",
                    apps.core.models.unsigned.UnsignedAutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Task ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("publish", "Publish")],
                        db_column="action",
                        default="publish",
                        help_text="Semantic verb the game must replay.",
                        max_length=32,
                        verbose_name="Action",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        db_column="actor",
                        default="System",
                        help_text="Staff attribution for the announcement.",
                        max_length=64,
                        verbose_name="Actor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        db_column="status",
                        default="pending",
                        help_text="Queue lifecycle: pending, done, or error.",
                        max_length=16,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(
                        db_column="attempts", default=0, verbose_name="Attempts"
                    ),
                ),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        db_column="last_error",
                        max_length=255,
                        null=True,
                        verbose_name="Last Error",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="created_at",
                        null=True,
                        verbose_name="Created At",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        db_column="processed_at",
                        null=True,
                        verbose_name="Processed At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patch Note Sync Task",
                "verbose_name_plural": "Patch Note Sync Tasks",
                "db_table": "patch_notes_sync_queue",
                "ordering": ("id",),
                "managed": False,
            },
        ),
    ]
